<?php


class Comment_Walker extends Walker_Comment
{
    public function start_lvl(&$output, $depth = 0, $args = array())
    {
        $GLOBALS['comment_depth'] = $depth + 1;

        switch ($args['style']) {
            case 'div':
                break;
            case 'ol':
                $output .= '<ol class="comments__list comments__list--child">' . "\n";
                break;
            case 'ul':
            default:
                $output .= '<ul class="comments__list comments__list--child">' . "\n";
                break;
        }
    }

    public function end_lvl(&$output, $depth = 0, $args = array())
    {
        $GLOBALS['comment_depth'] = $depth + 1;

        switch ($args['style']) {
            case 'div':
                break;
            case 'ol':
                $output .= "</ol><!-- .children -->\n";
                break;
            case 'ul':
            default:
                $output .= "</ul><!-- .children -->\n";
                break;
        }
    }

    public function display_element($element, &$children_elements, $max_depth, $depth, $args, &$output)
    {
        return parent::display_element($element, $children_elements, $max_depth, $depth, $args, $output); // TODO: Change the autogenerated stub
    }

    public function start_el(&$output, $comment, $depth = 0, $args = array(), $id = 0)
    {
        $depth++;
        $GLOBALS['comment_depth'] = $depth;
        $GLOBALS['comment'] = $comment;

        if (('pingback' == $comment->comment_type || 'trackback' == $comment->comment_type) && $args['short_ping']) {
            ob_start();
            $this->ping($comment, $depth, $args);
            $output .= ob_get_clean();
        } else {
            ob_start();
            $this->html5_comment($comment, $depth, $args);
            $output .= ob_get_clean();
        }
    }

    public function end_el(&$output, $comment, $depth = 0, $args = array())
    {
        if ('div' == $args['style'])
            $output .= "</div><!-- #comment-## -->\n";
        else
            $output .= "</li><!-- #comment-## -->\n";
    }

    protected function html5_comment($comment, $depth, $args)
    {
        global $post;
        $tag = ('div' === $args['style']) ? 'div' : 'li';
        $classes = $this->has_children ? ' comment--has-children' : ' comment--no-children';
        $comments_wrapper = '';
        if ($depth == 1) {
            $comments_wrapper = 'comments__wrapper col s12 m12';
            $classes .= ' card-panel z-depth-1';
//            $classes .= ' card-panel grey lighten-5 z-depth-1';
        }

        $author_class = $comment->user_id === $post->post_author ? 'author__name--post-author' : '';
        $avatar_size = isset($args['avatar_size']) ? $args['avatar_size'] : 80;
        $avatar = get_avatar($comment, $avatar_size, "", "", ['class' => 'circle responsive-img']);
        ?>

        <<?php echo $tag; ?> class="<?php echo $comments_wrapper; ?> col s12">
    <div id="comment-<?php comment_ID(); ?>" <?php comment_class($classes, $comment); ?>>
        <article id="comment-<?php comment_ID(); ?>" class="comment">
            <footer class="comment__meta">
                <div class="author valign-wrapper">
                    <?php if ($avatar) : ?>
                        <div class="author__avatar col s4 m2">
                            <?php echo $avatar; ?>
                        </div>
                    <?php endif; ?>
                    <div class="author__meta col s8 <?php if ($avatar) echo 'm10'; else echo 'm12'; ?>">
                        <?php printf(__('%s'), sprintf('<span class="author__name %s">%s</span>', $author_class, get_comment_author_link($comment))); ?>
                        <div class="author__name--meta">
                            <a href="<?php echo esc_url(get_comment_link($comment, $args)); ?>">
                                <time datetime="<?php comment_time('c'); ?>">
                                    <?php
                                    /* translators: 1: comment date, 2: comment time */
                                    printf(__('%1$s at %2$s'), get_comment_date('', $comment), get_comment_time());
                                    ?>
                                </time>
                            </a>
                            <?php edit_comment_link(__('Edit'), '<span class="edit-link">', '</span>'); ?>
                        </div>
                    </div>
                    <!-- .comment-metadata -->
                </div>
                <!-- .comment-author -->

                <?php if ('0' == $comment->comment_approved) : ?>
                    <p class="comment-awaiting-moderation"><?php _e('Your comment is awaiting moderation.'); ?></p>
                <?php endif; ?>
            </footer>
            <!-- .comment-meta -->

            <div class="comment__content">
                <p>
                    <?php comment_text(); ?>
                </p>
            </div>
            <!-- .comment-content -->

            <?php
            comment_reply_link(array_merge($args, array(
                'add_below' => 'comment',
                'depth' => $depth,
                'respond_id' => 'js-comment__form',
                'max_depth' => $args['max_depth'],
                'before' => '<div class="comment__reply"><button class="waves-effect waves-light btn btn-small btn--comment"><i class="material-icons left">reply</i>',
                'after' => '</button></div> '
            )));
            ?>
        </article>
        <!-- .comment-body -->
        <?php
    }

}